# Generated by Django 5.1.1 on 2024-11-12 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answered_question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.question', verbose_name='question'),
            preserve_default=False,
        ),
    ]
