# Generated by Django 5.1.1 on 2024-11-12 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_answer_answered_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='answerlike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(choices=[(1, 'like'), (-1, 'dislike')], verbose_name='value')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.answer', verbose_name='answer')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.profile', verbose_name='profile')),
            ],
            options={
                'verbose_name': 'answerlike',
                'verbose_name_plural': 'answerlikes',
            },
        ),
        migrations.CreateModel(
            name='questionlike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(choices=[(1, 'like'), (-1, 'dislike')], verbose_name='value')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.profile', verbose_name='profile')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.question', verbose_name='question')),
            ],
            options={
                'verbose_name': 'questionlike',
                'verbose_name_plural': 'questionlikes',
            },
        ),
    ]
