# Generated by Django 5.1.1 on 2024-11-12 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_answerlike_questionlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answered_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='web.question', verbose_name='question'),
        ),
    ]
