# Generated by Django 5.1.1 on 2024-11-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_answer_answered_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(upload_to='uploads', verbose_name='avatar'),
        ),
    ]
