# Generated by Django 5.1.1 on 2024-11-13 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answerlike',
            unique_together={('answer', 'profile')},
        ),
        migrations.AlterUniqueTogether(
            name='questionlike',
            unique_together={('question', 'profile')},
        ),
    ]
