# Generated by Django 5.1.1 on 2024-12-24 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_answerlike_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='question',
            name='rating',
        ),
    ]
