# Generated by Django 5.1.1 on 2024-12-25 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_rename_profile_questionlike_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answerlike',
            old_name='profile',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='answerlike',
            old_name='answer',
            new_name='liked_answer',
        ),
        migrations.AlterUniqueTogether(
            name='answerlike',
            unique_together={('liked_answer', 'author')},
        ),
    ]
